---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.serviceName }}
  labels:
    app: {{ .Values.serviceName }}
    version: "{{ .Values.imageTag }}"
spec:
  replicas: {{ .Values.numOfPods | default 2 }}
  selector:
    matchLabels:
      app: {{ .Values.serviceName }}
  template:
    metadata:
      labels:
        app: {{ .Values.serviceName }}
        version: "{{ .Values.imageTag }}"
    spec:
      {{- if (.Values.acrSecretName) }}
      imagePullSecrets:
        - name: {{ .Values.acrSecretName }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds | default 30 }}
      volumes:
        - name: namenode-dir
          hostPath:
            path: {{ .Values.hostPathNamenode }}
        - name: admin-keytab  # ✅ Ensure correct naming
          hostPath:
            path: {{ .Values.hostPathKeytab }}  # Persist admin keytab for sidecar only
        - name: config
          hostPath:
            path: {{ .Values.hostPathConfig }}
        - name: hdfs-keytabs
          emptyDir: {}  # Temporary volume for dynamically generated keytabs
      containers:
        - name: hadoop-namenode
          image: {{ .Values.dockerRepo }}pegacorn-fhirplace-namenode:{{ .Values.imageTag }}
          imagePullPolicy: {{ .Values.imagePullPolicy | default "IfNotPresent" }}
          env:
            - name: TRUSTSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.serviceName }}-secrets
                  key: truststorePassword
            - name: KEY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.serviceName }}-secrets
                  key: keyPassword
            - name: REALM
              value: REALM.TLD
            - name: CLUSTER_NAME
              value: {{ .Values.clusterName }}
            - name: HELM_RELEASE_TIME
              value: "{{ date "20060102-150405" .Release.Time }}"
            - name: KUBERNETES_SERVICE_NAME
              value: {{ .Values.serviceName }}
            - name: KUBERNETES_NAMESPACE
              value: {{ .Release.Namespace }}
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
          ports:
            - containerPort: 8020
              name: namenode
            - containerPort: 9871
              name: hadoop-web
          livenessProbe:
            tcpSocket:
              port: 9871
            initialDelaySeconds: 15
          readinessProbe:
            tcpSocket:
              port: 9871
            initialDelaySeconds: 15
          volumeMounts:
            - name: namenode-dir
              mountPath: /hadoop/dfs/namenode
            - name: hdfs-keytabs
              mountPath: /etc/security/hdfs-keytabs
            - name: config
              mountPath: /etc/hadoop/ssl
        # ------------------------ #
        # Sidecar for Keytab Management
        # ------------------------ #
        - name: kerberos-sidecar
          image: {{ .Values.dockerRepo }}kerberos-sidecar:{{ .Values.imageTag }}
          env:
            - name: REALM
              value: REALM.TLD
            - name: KUBERNETES_SERVICE_NAME
              value: {{ .Values.serviceName }}
            - name: KUBERNETES_NAMESPACE
              value: {{ .Release.Namespace }}
            - name: HELM_RELEASE_TIME
              value: "{{ date "20060102-150405" .Release.Time }}"
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
          volumeMounts:
            - name: hdfs-keytabs
              mountPath: /etc/security/hdfs-keytabs # Stores dynamically generated keytabs
            - name: admin-keytab  # ✅ Matches the volume name above
              mountPath: /etc/security/admin-keytab